### ISSUE TITLE
Likers Blocker does not show blocking option

### ISSUE THREAD

**Issue by FirenaFirena** [dmstern/likers-blocker#107]
Installed, but next to the list of people who liked tweets there is no option to block.

**Comment by dmstern** [comment]
Hey @FirenaFirena,

thanks for your report.
Could you please provide some more information to reproduce the issue? 

* Which browser are you using?
* Which OS?
* Have you any other extensions installed that manipulate the twitter UI (like GoodTwitter)?

**Comment by FirenaFirena** [comment]
Hi Daniel,
danke für deine Antwort. Ich habe es aktuell mit Firefox probiert (Version 109.0) auf Windows 10. An zusätzlichen Add ins verwende ich:- I don´t care about cookies- Language Tool
Mehr nicht.
Voll nett dass du so schnell antwortest, danke!
Meine Liste sieht derzeit so aus:Da erscheint leider nirgendwo die Option, alle "Liker" zu blocken...




    Am Freitag, 20. Januar 2023 um 10:14:28 MEZ hat Daniel Morgenstern ***@***.***> Folgendes geschrieben:  
 
 


Hey @FirenaFirena,

thanks for your report.
Could you please provide some more information to reproduce the issue?
   
   - Which browser are you using?
   - Which OS?
   - Have you any other extensions installed that manipulate the twitter UI (like GoodTwitter)?

**Comment by dmstern** [comment]
Deinen Screenshot kann ich leider nicht sehen. kannst du den nochmal hier bei GitHub direkt posten? Ich glaube, der wird vom E-Mail-Programm geschluckt.

**Comment by FirenaFirena** [comment]
Klar, gerne! Ich hoffe es klappt:
![FBD5A86F-54AD-4FCF-A4EA-3A0884874EB6](https://user-images.githubusercontent.com/123156579/213941259-296dc122-77f4-4005-bed3-32a2eff1b6e7.jpeg)

**Comment by dmstern** [comment]
Ah! Danke, ja das hilft. Klick mal bitte auf den Tweet, dann auf die Anzahl der Likes. 

![grafik](https://user-images.githubusercontent.com/5219707/213942954-2f5427d6-3e64-4553-b0ba-d6e887856fce.png)

Dann müsste sich ein Popup öffnen, wo rechts oben der "Alle blockieren"-Button erscheint.

![grafik](https://user-images.githubusercontent.com/5219707/213942982-566f7147-199d-43ae-a87c-a27cf74ea68b.png)

Diese Ansicht aus deinem Screenshot mit der Überschrift "Das gefällt jemandem" kenne ich nur aus den Mitteilungen für die Likes auf eigene Tweets.

![grafik](https://user-images.githubusercontent.com/5219707/213943010-53145a5d-038f-440e-a502-173ded6463c1.png)

**Comment by FirenaFirena** [comment]
Super, danke! Probiere ich morgen gleich aus wenn ich wieder am PC sitze.
Ich hab aber tatsächlich den Screenshot gemacht von Tweets, die jemand anderes verfasst hatte. Allerdings ging es da um Antworten auf einen Thread von mir. 
Danke jedenfalls für die Mühe, ich geb Rückmeldung! 




Am Sonntag, Januar 22, 2023, 11:12 PM schrieb Daniel Morgenstern ***@***.***>:




Ah! Danke, ja das hilft. Klick mal bitte auf den Tweet, dann auf die Anzahl der Likes.



Dann müsste sich ein Popup öffnen, wo rechts oben der "Alle blockieren"-Button erscheint.



Diese Ansicht aus deinem Screenshot mit der Überschrift "Das gefällt jemandem" kenne ich nur aus den Mitteilungen für die Likes auf eigene Tweets.

**Comment by FirenaFirena** [comment]
Hallo Daniel,

wir sind ein ganzes Stück weiter! Die Option "Alle Blockieren" erscheint jetzt:
![grafik](https://user-images.githubusercontent.com/123156579/214272857-a478eae5-dd97-400f-8979-33b59ba28dac.png)


 Aaaaber: Wenn ich das auswähle, wird zwar nach den Accounts gesucht, aber ich kann das endgültige Blocken nicht bestätigen. Ich kann entweder abbrechen, oder die Liste kopieren...:

![grafik](https://user-images.githubusercontent.com/123156579/214272971-f829e7d0-91bc-4ef6-96ed-1c6d56a19891.png)

Wenn ich auf "Auswählen" klicke erscheint sowas:

![grafik](https://user-images.githubusercontent.com/123156579/214273089-333651a7-6a62-454d-b390-0acae5ed1e6b.png)

Aber die gefundenen Accounts sind immer noch nicht geblockt.

Sorry für die Umstände. Ich bin vermutlich der unfähigste User eurer App seit Ewig.

**Comment by dmstern** [comment]
Kein Problem. :)
Dort musst du einmal auf "Sign in with Tiwtter" klicken. Damit erlaubst du dem Blockservice unter ichbinhier-twittertools.herokuapp.com/ auf auf deinen Twitter-Account zuzugreifen, damit das Blocken automatisiert werden kann.
Du wirst dann weitergeleitet zu einer Bestätigungsseite, auf der die zu blockenden Accounts aufgelistet und alle angehakt sind. Dort musst du dann nochmal auf "Blocken" klicken. Wenn am Ende eine Seite mit der Meldung "Success" erscheint, sollte es geklappt haben. :)

**Comment by FirenaFirena** [comment]
Hat geklappt! Vielen vielen Dank für deine Geduld und die Anleitung!!!

    Am Dienstag, 24. Januar 2023 um 20:00:51 MEZ hat Daniel Morgenstern ***@***.***> Folgendes geschrieben:  
 
 


Kein Problem. :)
Dort musst du einmal auf "Sign in with Tiwtter" klicken. Damit erlaubst du dem Blockservice unter ichbinhier-twittertools.herokuapp.com/ auf auf deinen Twitter-Account zuzugreifen, damit das Blocken automatisiert werden kann.
Du wirst dann weitergeleitet zu einer Bestätigungsseite, auf der die zu blockenden Accounts aufgelistet und alle angehakt sind. Dort musst du dann nochmal auf "Blocken" klicken. Wenn am Ende eine Seite mit der Meldung "Success" erscheint, sollte es geklappt haben. :)

**Comment by dmstern** [comment]
Großartig. :) Kein Problem. Dann können wir das Issue ja feierlich schließen.

**Comment by FirenaFirena** [comment]
Schicke dir virtuell einen Schnaps rüber (oder einen Beruhigungstee). 😉 Hast du dir verdient.




Am Mittwoch, Januar 25, 2023, 11:02 PM schrieb Daniel Morgenstern ***@***.***>:




Großartig. :) Kein Problem. Dann können wir das Issue ja feierlich schließen.

**Comment by dmstern** [comment]
Cheers! 🥂
