### ISSUE TITLE
Buttons to block are not visible

### ISSUE THREAD

**Issue by akmesul** [dmstern/likers-blocker#108]
Can not find buttons to block. Google Chrome Version 109.0.5414.75 (Official Build) (64-bit)
![image](https://user-images.githubusercontent.com/123184043/213730472-838cf9ac-cf78-4944-ac43-5eb3733c55b8.png)

**Comment by SysAdminDoc** [comment]
The "Select" button is what you push to block.

**Comment by dmstern** [comment]
@akmesul what @SysAdminDoc says.
I replaced the label from "block" to "select" to make it more clear that the click on this button won't trigger the block action but the user has to select accounts and confirm the block action in the next step. 
But maybe this should be a reminder for me to update to tutorial page. :)
