### ISSUE TITLE
Arch Linux - Firefox Dev. - Firefox - Add-on neueste Ver.

### ISSUE THREAD

**Issue by Sternen-Wolf** [dmstern/likers-blocker#120]
Leider lässt sich die ZIP nicht installieren. Bei beiden Browsern gibt es eine Fehlermeldung, das Add-On sei beschädigt.

Gibt es eine Lösungsmöglichkeit? Danke

By the way: Gute Arbeit!

**Comment by dmstern** [comment]
Danke! :)

Ich glaube, das hat irgendwas mit Zertifikaten oder so zu tun... versuch mal, das ZIP zu entpacken und stattdessen den entpackten Ordner-Inhalt als temporäres Add-On im Browser zu laden.

**Comment by Sternen-Wolf** [comment]
Danke für die Antwort. Für das temporäre Laden bin ich zu blöd und finde keine Anleitung.

Wenn ich allein das Problem habe, dann muss es ja bei allen anderen funktionieren. Ich warte mal, vielleicht kommt ja noch was.

**Comment by Sternen-Wolf** [comment]
YAEAH! YOU DID IT! - Update is working. From now on You are my star :-)

**Comment by dmstern** [comment]
Großartig. Danke und viel Spaß beim Blocken! :)
