### ISSUE TITLE
Advanced Instructions

### ISSUE THREAD

**Issue by Ch4rg3r** [dmstern/likers-blocker#28]
Hey,

additional install instructions for those who can't activate the extension. Unpacking it to a folder and using "Load Unpacked" fixes this issue.

**Comment by dmstern** [comment]
@Ch4rg3r I would rather add a notice that users who can't install the package should wait until it's available in the chrome web store, because then it's easier to ship updates.
The extension is already submitted, just waiting for the approval (see #19).

**Comment by dmstern** [comment]
See also https://github.com/dmstern/likers-blocker#development

The "Load unpacked" part is already there for advanced users. ;)
