### ISSUE TITLE
shifted popup content

### ISSUE THREAD

**Issue by dmstern** [dmstern/likers-blocker#32]
https://twitter.com/Pertsch/status/1233788140218994688?s=20

![image](https://user-images.githubusercontent.com/5219707/75611298-b2c84200-5b19-11ea-849c-06f6ee2860af.png)

**Comment by SebastianBerlin** [comment]
> ![image](https://user-images.githubusercontent.com/5219707/75611298-b2c84200-5b19-11ea-849c-06f6ee2860af.png)

Win 10, Firefox 73.0.1

Active extensions, which may have an influence: HTTPS Everywhere, Privacy Badger, uBlock Origin.

**Comment by dmstern** [comment]
@SebastianBerlin unfortunately, I could not completely reproduce this issue.

But I've got an idea what could be wrong and committed a fix.

Please inform me if the issue still remains after the next release.
