### ISSUE TITLE
Plugin not working on Tweetdeck yet

### ISSUE THREAD

**Issue by jastBytes** [dmstern/likers-blocker#56]
The plugin is awesome but does not work for https://tweetdeck.twitter.com/. It would be great to have the same functionality there.

**Comment by dmstern** [comment]
Hey @jastBytes,

thank you for your suggestion. At the moment this seems a bit too complicated, because the Tweetdeck UI is very different from the original Twitter UI and the variability is on a very high level so it seems very hard to hook a button into this UI and scrape users from it.
