### ISSUE TITLE
Doesnt block anyone (chrome) please fix because your tool can be very useful

### ISSUE THREAD

**Issue by nose432** [dmstern/likers-blocker#57]
I try to prove it in a tweet of 6 likes of a person (only to prove it) when i press block all says blocking everyone but when i check the same users are not blocked is like if the extension simulates that block them but is not i prove it again but nothing i dont know if i have to use another navigator like firefox or opera but i hope you can fix that soon because it could be a very useful extension (note english is not my first language sorry if something is wrong)

**Comment by nose432** [comment]
and also from what i read in your reviews you can share the block list (is possible to do this without affecting the author) 
Lets say i want to help somebody

**Comment by dmstern** [comment]
Dear @nose432,
Your fist issue report is already tracked in #64.
Your second report seems to be already tracked in #69.
Closing this one.
