### ISSUE TITLE
Dont see the authorization option

### ISSUE THREAD

**Issue by aotdstix** [dmstern/likers-blocker#60]
in twitter>settings>security>apps>connected apps, i cant see the extension. the usage tab also doesnt tell me what to do, just "authorize the extension" but i dont know where. i dont get any popups either

**Comment by dmstern** [comment]
Hey @aotdstix,

You should see "#ichbinhierApp" under "conected apps" since the Likers Blocker uses the [ichbinhier](https://ichbinhier-twittertools.herokuapp.com/) backend API.

![grafik](https://user-images.githubusercontent.com/5219707/134803749-a6add322-c8dc-4f3a-aafc-7c4bea0eb924.png)
