### ISSUE TITLE
More blocks but with a URL?

### ISSUE THREAD

**Issue by Sacred-Shadow** [dmstern/likers-blocker#62]
Browser: Opera GX
Addon version: 2.3.2 over the addon Store

For some time now, more than 80 entries have been scanned. In some cases, the scans are now up to 160 entries.
Could it be that Twitter is now showing more people?

Then I noticed that for a few weeks now, URLs have been appearing regularly instead of usernames. Example in the picture:
![image](https://user-images.githubusercontent.com/61997661/144206438-dc4ae88d-d9df-4071-89c7-291b599581b4.png)

**Comment by dmstern** [comment]
Hi @Sacred-Shadow,

thank you for your bug report. You're right, this should not happen. I will investigate this as soon as I can.

Regards,
Daniel

**Comment by dmstern** [comment]
@Sacred-Shadow could you please check if this issue has been fixed by v2.3.3?

**Comment by Sacred-Shadow** [comment]
@dmstern I have now spread over 1200 blocks ... so far no more URLs. So it seems to be working.
