### ISSUE TITLE
[Bug] Keine User in der Sammlung

### ISSUE THREAD

**Issue by Sacred-Shadow** [dmstern/likers-blocker#63]
Hey Daniel,

vor ca. einer Woche ist mir aufgefallen, dass zwar die Liste der User schön lang ist ABER bei der Erstellung keine User gesammelt werden.
Wenn doch mal 1 User drin ist, ist das bei der Übermittlung dann kein Username sondern eine URL. (s. #62 ) 

Irgendwas ist gerade also echt faul :( 

Kannst du mal schauen?
Oder liegt es nur an meinem System hier?

Grüße

**Comment by Sacred-Shadow** [comment]
@dmstern danke für die schnelle Hilfe bei dem Update.
Im Opera hab ich jedoch ein komisches Verhalten entdeckt.

Werden in einem Tweet weniger als 10 User gefunden (Sammle Nutzernamen ein...) kommt dann unten immer 0 Nutzer gefunden. Sobald es mehr als 10 sind, geht es wieder. (zumindest soweit ich das bisher sehen kann)

Kann das jemand gegen checken?

**Comment by dmstern** [comment]
@Sacred-Shadow interessante Beobachtung. Ich schau mal, warum die Extension hier so hungrig nach usern ist und immer mindestens gleich 10 auf einmal haben möchte.

**Comment by Sacred-Shadow** [comment]
Höhö ... wer weiß evtl. hat sie ja Geschmack an einigen Gruppen gefunden.
Ist der Hinweis mit den 80 eigentlich noch aktuell? 

Mir hatte er gerade 335 Nicks eingesammelt .. .wurden auch alle sauber übertragen. 
Klappt dann auch im Nachgang der Block von allen oder bleibts dann irgendwann später bei den 80 hängen?

**Comment by dmstern** [comment]
Oh interessant, das habe ich noch gar nicht beobachtet. Wäre natürlich schön, wenn Twitter sich da bisschen geöffnet hat. Technisch gesehen wird das frontend-seitig nicht nochmal beschränkt. Ich check das mal aus und passe ggf. den Hinweis an. Danke!

**Comment by Sacred-Shadow** [comment]
Ich hab mal die letzten in der Liste getestet .. also wohl 330-335 ... wurden erfolgreich geblockt. 
Sind also wohl durch gegangen :D 

Danke dir für deine Mühe
