### ISSUE TITLE
Empty small block lists (Chrome / Edge)

### ISSUE THREAD

**Issue by Dhizaes** [dmstern/likers-blocker#64]
Hi,
I'm using this extension for a long time in Microsoft Edge. I can't get user list for a while. It just collects zero user and the block list is completely empty or shows some random Twitter links. When i try to block empty list it isn't block anyone. Sometimes when thousands of user in list, it just keep scrolling infinitely and adds 1 user to the collected user list almost every 10-30 second and sometimes user count just stuck but keeps scrolling anyway. I tried to disable and enable again, i tried to reinstall extension, still same issue happens.

**Comment by Sacred-Shadow** [comment]
#63

**Comment by nichu42** [comment]
Same here on Microsoft Edge 98.0.1108.15. It has worked perfectly in the past. Now the extension scrolls through the list until the very end and hangs at "..." without ever showing the block page. I just tested a few tweets: With 14 users it stops at 13, with 21 it stops at 20, with 58 it stops at 55, with 189 it stops at 170. If it doesn't have to scroll (let's say with 3 users only) the result shown is "0 Nutzer gefunden."

I wish you could make it work again - it's such a wonderful and time-saving extension.

**Comment by dmstern** [comment]
The original issue #63 is already fixed, but the fix was rejected by the Chrome Web Store. Still trying to figure out why exactly.

**Comment by dmstern** [comment]
Fixed by https://github.com/dmstern/likers-blocker/releases/tag/v2.3.7
