### ISSUE TITLE
Limit erhöhen

### ISSUE THREAD

**Issue by Sacred-Shadow** [dmstern/likers-blocker#71]
Hey zusammen,

ist es möglich das Limit im Scan zu erhöhen?
Twitter begrenzt die Anzahl der angezeigten Liker ja nicht mehr - man kann (wenn man die Zeit hat) auch gut bis 1000 scrollen.

Aber das Addon bricht beim Sammeln zwischen 320-330 ab.
Obwohl man im Likes Fenster weiter scrollen kann und auch neue Namen kommen.

Bekommen wir es evtl. hin, alles einzusammeln? 

Grüße

**Comment by dmstern** [comment]
Hey! Ja, das würde theoretisch (frontend-seitig) gehen. Das Problem ist, dass wir anschließend einen sehr langen Link an die Block-API übertragen müssen und da stoßen wir an eine technische Grenze.
Man könnte halt:

1. (vergleichsweise einfach) die Liste an zu blockenden Accounts in mehrere Links aufteilen (so wie das aktuell bereits bei der Export-Funktion auch schon gemacht wird), die dann in separaten Browser-Tabs oder nacheinander geöffnet werden
2. oder (aus Nutzer:innen-Sicht sicher die bequemere Variante): Den API-Request auf einen POST-Request umstellen, sodass die Liste an zu blockenden Accounts als Payload mitgeschickt werden kann. Hier müssten wir mal mit @pkreissel sprechen und vermutlich auch die Authentifierung umbauen.
