### ISSUE TITLE
Collecting Likers hangs indefinitely

### ISSUE THREAD

**Issue by andreas-wolf** [dmstern/likers-blocker#73]
On Linux Chromium Version 99.0.4844.51 

Most of the time users are collected the collection hangs at the end of the scroll window. There are only the three dots moving. Same  for retweet list.

![image](https://user-images.githubusercontent.com/10654315/157064319-6ed3035a-9d48-47f1-a858-53cb15bb4ed9.png)

**Comment by andreas-wolf** [comment]
I think it's related to https://github.com/dmstern/likers-blocker/blob/9092896bd3f86e24fb652e97f10035ea6561ab35/src/LikersBlocker.ts#L523-L524

I see 
```
t.scrollTop
15128.7998046875
t.scrollHeight - t.clientHeight
15129
```

If I set a breakpoint and `scrolledToBottom=true` it continues normally.

**Comment by dmstern** [comment]
Hey @andreas-wolf,

kannst du es mal mit der neuen version 3.0 ausprobieren, ob das Problem behoben ist? https://github.com/dmstern/likers-blocker/releases/tag/v3.0.0

Es gibt jetzt für derartige "Verhakungen" zur Not einen "Vorspulen"-Button, vielleicht hilft das ja. ;)

Bisher hat nur Firefox die neue Version akzeptiert, aber du kannst über die Extensions-Seite in deinem Chromium die im Release angehängte .zip-Datei lokal laden. Am besten vorher die Original-Extension deinstallieren.

**Comment by andreas-wolf** [comment]
Hi @dmstern,

ja das geht. 
Danke für das prompte fixen.

Ich möchte gerne einen kleinen Verbesserungsvorschlag machen.

Ich sehe im Diff, dass da jetzt ein allowanceOffset hinzukam:
[https://github.com/dmstern/likers-blocker/commit/3fb76f82ce1c555a41331e0fd7a6c7d8903b433d#diff-02d804992621ce9b75bcb3ff8e887d20c5ee3facfa047979c1ead7731610ea21R522](https://github.com/dmstern/likers-blocker/commit/3fb76f82ce1c555a41331e0fd7a6c7d8903b433d#diff-02d804992621ce9b75bcb3ff8e887d20c5ee3facfa047979c1ead7731610ea21R522)

```
		scrolly.scrollTop >=
			scrolly.scrollHeight - scrolly.clientHeight - allowanceOffset;
```

Ich habe versucht den Fehler einzugrenzen und herausgefunden, dass der Fehler dann auftritt, wenn die Webseite gezoomt ist (z.B. 150%).
Es gibt auch ein entsprechendes Warning in der Doku von [scrollTop](https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollTop):

**Warning: On systems using display scaling, scrollTop may give you a decimal value.**

Daher mein Vorschlag:

```
Math.ceil(scrolly.scrollTop) >= scrolly.scrollHeight - scrolly.clientHeight;
```

Ich glaube das ist besser als der (willkürliche) Offset. 
Das Match.ceil() funktioniert bei mir genauso gut.

**Comment by dmstern** [comment]
Oha genial, danke! :) Möchtest du einen Pull Request stellen und damit in der Contributors-Liste auftauchen? ;)

Das allowanceOffset hatte ich eingebaut, weil ich einen Fall beobachtet hatte, wo die eine Seite der Bedinung gerade um einen Pixel zu niedrig war um erfüllt zu werden. Hab dann sicherheitshalber noch ein bisschen mehr drauf geschlagen. Aber wenn das `Math.ceil` das auch mit abdeckt, umso besser, da gebe ich dir vollkommen recht. :)

**Comment by dmstern** [comment]
Danke @andreas-wolf, habe deinen Vorschlag in den master-branch übernommen. :)
