### ISSUE TITLE
service error

### ISSUE THREAD

**Issue by nyamaries** [dmstern/likers-blocker#81]
I tried to block a tweet with around 36k likes, which came up to 196 parts. It worked up until around the 98th, when I got an error message instead of the block list showing up. Instead of me being able to see all the usernames and a block button, It just showed "Service Error (500)". I waited around 10 minutes, and it started working again, but it also gave me the error message again after a little bit. I wasn't sure if it was just because the tweet was too big but just wanted to let you know
<img width="1440" alt="Screen Shot 2022-03-24 at 3 40 36 PM" src="https://user-images.githubusercontent.com/102323980/159997089-88f4a960-440a-410e-beaa-95bf0c8f5f82.png">

**Comment by dmstern** [comment]
Hey @nyamaries,

thanks for your report. wow, 36k... 😲 maybe we exceed some API limit here for that big numbers. I will have a look into this soon and maybe implement a warning or something to catch this error.

**Comment by dmstern** [comment]
seems stale -> closing this.
