### ISSUE TITLE
Where do I click to continue?

### ISSUE THREAD

**Issue by max73456** [dmstern/likers-blocker#82]
![Screenshot 2022-03-25 1 41 22 AM](https://user-images.githubusercontent.com/102353280/160086588-d294f6e7-c854-4336-91f7-05e3cafba1c0.png)
So, uh... yeah. There's no button to continue from here. I've attached a screenshot to show as much.

**Comment by max73456** [comment]
I've tried clicking on that little grey thing on the right, but it doesn't do anything.

**Comment by max73456** [comment]
Ah. Finally figured it out. I need to scroll down.

**Comment by dmstern** [comment]
Hey @max73456, yeah it can happen that there are too many results to display in the small dialog, so you have to scroll down. maybe I should put a `min-height` here to show at least one list entry if the dialog is as small as in your screenshot...? 🤔 
But I guess in one of the next releases we can get rid of this dividing-into-serveral-links-thing either way so this issue will be fixed as well. I'll close this issue then if that's ok for you.
