### ISSUE TITLE
Mis-count when a tweet has a "K" in its Like count.

### ISSUE THREAD

**Issue by XStylus** [dmstern/likers-blocker#83]
Likers Blocker seems to mis-count any tweet whose "like" counter has a K in it.

For example: If a tweet to be blocked has "37K" likes (meaning approximately 37,000 likes), the Likers Blocker progress bar will consider "37" blocked tweets to be 100%.

Another example: If a tweet to be blocked as 104.7K likes (meaning approximately 104,700 likes) the Likers Blocker progress bar will consider "1,047" blocked tweets to be 100%.

**Comment by dmstern** [comment]
@XStylus thank you for your bug report. This issue has been fixed in the new release https://github.com/dmstern/likers-blocker/releases/tag/v3.1.4 and will land in the stores soon.
