### ISSUE TITLE
hi

### ISSUE THREAD

**Issue by parhammhe** [dmstern/likers-blocker#93]
I am receiving the following error :
Twitter API returned a 401 (Unauthorized), Invalid / expired To ken

**Comment by dmstern** [comment]
Please try to avoid opening multiple ichbinhiertwittertools tabs before authenticating the app.
Could you please try to logout of ichbinhiertwittertools, login again and try again?

**Comment by dmstern** [comment]
I'll close this for now. If the error does occur again, feel free to open a new one (may with a more expressive title ;))
