### ISSUE TITLE
Does not work in Edge or Chrome

### ISSUE THREAD

**Issue by Bartfratze1982** [dmstern/likers-blocker#94]
I tried the plugin both in Edge and Chrome for the first time this weekend, it only worked once (in Edge) and I have no idea why. I can't replicate it. I deleted and re-installed the plugin, I tried logging out and in again, I never get the "block all" button. I also tried different urls, like mobile.twitter.com and the regular www.twitter.com.

**Comment by diesocke** [comment]
Same here. I got it to work in Firefox, however.

**Comment by mostafaznv** [comment]
doesn't work in chrome.
progress bar works well and at the end, it says N followers have been blocked but it isn't true. all of them are not-blocked and my block list is empty.

any advice?

**Comment by corneliusroemer** [comment]
@mostafaznv use Firefox

**Comment by diesocke** [comment]
Am 10. Oktober 2022 14:37:03 UTC schrieb Cornelius Roemer ***@***.***>:
***@***.*** use Firefox

No good advice for people whose employer's IT won't allow installing Firefox.

-- 
Oliver Ding, Kolberger Str. 79, 51381 Leverkusen
https://sockenseite.de/

**Comment by corneliusroemer** [comment]
Then log in to the Twitter account on a non-work computer.
Or run Firefox in a VM, either on your machine or in the cloud.
At least, it works on Firefox.

**Comment by mostafaznv** [comment]
So I suggest you delete chrome extension link in readme. it doesn't work at all.

**Comment by dmstern** [comment]
Hey guys, thank you all for your reports; I will look into that in the next few days. Thanks for your patience!

**Comment by corneliusroemer** [comment]
@mostafaznv it could be that it worked on old Chrome versions, maybe it's possible to restrict the versions on the Chrome store until this is fixed.

**Comment by dmstern** [comment]
A bugfix release has been published to the Chrome Web Store yesterday. It should work again: https://chrome.google.com/webstore/detail/likers-blocker/melnbpmfhaejmcpfflfjmchondkpmkcj :)

**Comment by mostafaznv** [comment]
Thank you @dmstern 
But it still doesn't work.
Should I do something special after updating the extension? (something like clear cache or ...)

**Comment by corneliusroemer** [comment]
it's probably only on master, not yet released

**Comment by mostafaznv** [comment]
I installed the zip version too. but nothing changed.

**Comment by dmstern** [comment]
> it's probably only on master, not yet released
@corneliusroemer yes, the new version is released in the web store.

@mostafaznv could you please describe the issue a bit more detailed and maybe attach a screenshot? Does the "block all" button appear at least? Could you please open the JavaScript console and check if there are any errors?

**Comment by mostafaznv** [comment]
After restarting my laptop, it seems it works great.

Sorry for the wrong report.

**Comment by dmstern** [comment]
@mostafaznv great! No problem. :)
I'll re-close this then. ^^
