### ISSUE TITLE
Blocklist does not work.

### ISSUE THREAD

**Issue by LifeVestedNeko** [dmstern/likers-blocker#95]
After going through the GUI process on twitter when the extension sends me to the site the site apparently does not exist.
On Firefox

**Comment by dmstern** [comment]
Could you please try to logout from ichbinhiertwittertools, re-login and try again?

**Comment by dmstern** [comment]
Maybe the blocklist service hosted on Heroku had a hick-up. I'll close this issue for now, feel free to open a new one if the error persists.
